<a href="https://colab.research.google.com/github/hrithikkumarp/ML/blob/main/DataSTD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.preprocessing import StandardScaler
data=[[1,2],[3,4],[5,6]]
scalar=StandardScaler()
sdata=scalar.fit_transform(data)
print("Original:\n")
print(data)
print("\nStandardized:\n")
print(sdata)

Original:

[[1, 2], [3, 4], [5, 6]]

Standardized:

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


In [ ]:
import pandas as pd
import numpy as np
auto=pd.read_csv("https://raw.githubusercontent.com/nunnarilabs/ml/master/Automobile_Data/automobile_data.csv")
auto.head()

symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3                 ?  alfa-romero       gas        std          two   
1          3                 ?  alfa-romero       gas        std          two   
2          1                 ?  alfa-romero       gas        std          two   
3          2               164         audi       gas        std         four   
4          2               164         audi       gas        std         four   

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
0  convertible          rwd           front        88.6  ...          130   
1  convertible          rwd           front        88.6  ...          130   
2    hatchback          rwd           front        94.5  ...          152   
3        sedan          fwd           front        99.8  ...          109   
4        sedan          4wd           front        99.4  ...          136   

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
0         mpfi  3.47    2.68               9.0        111      5000       21   
1         mpfi  3.47    2.68               9.0        111      5000       21   
2         mpfi  2.68    3.47               9.0        154      5000       19   
3         mpfi  3.19     3.4              10.0        102      5500       24   
4         mpfi  3.19     3.4               8.0        115      5500       18   

  highway-mpg  price  
0          27  13495  
1          27  16500  
2          26  16500  
3          30  13950  
4          22  17450  

[5 rows x 26 columns]

In [ ]:
auto['engine-size']=auto['engine-size']-auto['engine-size'].max() #Decresing the values to fit a range by decreasing by max()
auto['engine-size']

0     -196
1     -196
2     -174
3     -217
4     -190
      ... 
200   -185
201   -185
202   -153
203   -181
204   -185
Name: engine-size, Length: 205, dtype: int64

In [ ]:
auto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  205 non-null    object 
 2   make               205 non-null    object 
 3   fuel-type          205 non-null    object 
 4   aspiration         205 non-null    object 
 5   num-of-doors       205 non-null    object 
 6   body-style         205 non-null    object 
 7   drive-wheels       205 non-null    object 
 8   engine-location    205 non-null    object 
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64  
 14  engine-type        205 non-null    object 
 15  num-of-cylinders   205 non-null    object 
 16  engine-size        205 non

In [ ]:
auto['peak-rpm'].replace(np.nan,'0',inplace=True)

In [ ]:
auto['peak-rpm'].astype(int)

0      5000
1      5000
2      5000
3      5500
4      5500
       ... 
200    5400
201    5300
202    5500
203    4800
204    5400
Name: peak-rpm, Length: 205, dtype: int64

In [ ]:
auto['peak-rpm'].replace(0,auto['peak-rpm'].mean(),inplace=True)

In [ ]:
auto['peak-rpm'].astype(int)

0      5000
1      5000
2      5000
3      5500
4      5500
       ... 
200    5400
201    5300
202    5500
203    4800
204    5400
Name: peak-rpm, Length: 205, dtype: int64

In [ ]:
auto['peak-rpm']=auto['peak-rpm']/1000

TypeError: ignored

In [ ]:
from sklearn.preprocessing import MinMaxScaler
MinMax=MinMaxScaler()
MinMaxResult=MinMax.fit_transform(data)
MinMaxResult

array([[0. , 0. ],
       [0.5, 0.5],
       [1. , 1. ]])

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np
datax=np.array([[1,2],[3,4],[5,6]])
poly=PolynomialFeatures(degree=2)
xpoly=poly.fit_transform(datax)
print(xpoly)

[[ 1.  1.  2.  1.  2.  4.]
 [ 1.  3.  4.  9. 12. 16.]
 [ 1.  5.  6. 25. 30. 36.]]


In [ ]:
m=-1000
c=-1000
lr=0.001
epochs=5000

n=len(x)